# Enable GPIO driver support, used by the blinky sample
CONFIG_GPIO=y

# Enable NXP Touch library
CONFIG_NXP_TOUCH=y

# Enable logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

# Enable thread monitoring for debugger RTOS view support
CONFIG_THREAD_MONITOR=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_INIT_STACKS=y
CONFIG_DEBUG_THREAD_INFO=y